# Generated by Django 4.2.4 on 2025-01-05 20:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='C:\\Users\\MSUSERSL123\\PycharmProjects\\pythonProject\\ragsite', verbose_name='Document')),
            ],
        ),
    ]
